name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        tox-version: ["==3.18.0", "==3.19.0", "==3.20.0", ">=4.0.0a2"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install "tox${{ matrix.tox-version }}" .
      - name: Test with tox
        run: |
          pyversion="${{ matrix.python-version }}"
          if which tox4 > /dev/null
          then
            mv pdm.tox4.lock pdm.lock
            tox4 -e py${pyversion/./}
          else
            tox -e py${pyversion/./}
          fi
