name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        tox-version: ["==3.17", "==3.18.0", "==3.19.0", "==3.20.0", ""]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install tox${{ matrix.tox-version }} tox-gh-actions .
      - name: Test with tox
        run: |
          tox
        env:
          LD_PRELOAD: /lib/x86_64-linux-gnu/libgcc_s.so.1
